### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by jayvdb** [AvinashSingh786/RegAcquire#1]

**Comment by AvinashSingh786** [comment]
Hi @jayvdb, the source code is the bat file called "dump.bat". This was then packaged into an executable with a BatToExe converter.

**Comment by jayvdb** [comment]
Gotcha!  Which BatToExe converter are you using?  Is it open source? (so I can create my own exe after modifying it)

**Comment by AvinashSingh786** [comment]
Yes, you can modify the bat script and test using that. Creating your own exe is just for portability purposes and making it easier to run. Running the bat script in command prompt or PowerShell will yield the same result. I used https://www.battoexeconverter.com/ but there are other's available. Yeah, it is open source using the MIT License. My script uses 2 external programs FCIV which is Microsoft's file integrity checker which is a simple MD5 sum, and RawCopy which copies files that are constantly in use.

**Comment by jayvdb** [comment]
Thanks.
